import json,hashlib
from pathlib import Path
r=json.loads(Path('data/roster.json').read_text(encoding='utf-8'));old=json.loads(Path('data/roster-v7-backup.json').read_text(encoding='utf-8'));spec={m['id']:m for m in json.loads(Path('data/species_gen1_3.json').read_text(encoding='utf-8'))};traits=json.loads(Path('data/traits.json').read_text(encoding='utf-8'));aug=json.loads(Path('data/augments.json').read_text(encoding='utf-8'))
lines=['# Version 8 – Wirtschaft, Progression und Typen','', 'Die native Windows-Ausgabe startet im Vollbild. F11 wechselt zum Fenster. Power Green, Pixelrahmen und feste 2,5D-Perspektive bleiben erhalten. Browser-Vollbild wird im Web-Zweig direkt beim Startklick angefordert; ein Webexport ist in diesem Windows-Paket nicht enthalten und dieser Browserpfad wurde nicht ausgeführt.','', '## Wirtschaft','', 'Grundeinkommen: **6 Gold statt 7**, zuzüglich 1 Fortschrittsgold je fünf abgeschlossenen Runden. Zinsen: 1 je volle 10 gesparte Gold, maximal 5, berechnet vor der Auszahlung. Sieg: +2 Ergebnisgold, zusätzlich bis zu 3 Seriengold (je drei Siege +1). Niederlage: +3 Ergebnisgold. Augment-Einkommen bleibt zusätzlich erhalten. Unentschieden: keine Auszahlung und keine Erfahrung. Die Vorschau zeigt Sieg/Niederlage als Spanne; Zinsen sind darin bereits enthalten.','', 'Erfahrung pro Sieg: 3, pro Niederlage: 2, zuzüglich Augments. Kaufen: 4 EP für 4 Gold, mit bestehenden EP-Augments entsprechend mehr. Level 10 bleibt Maximum.','', '| Von Level | Zum nächsten Level benötigte EP |','|---|---|']
for i,v in enumerate([2,3,4,8,14,22,32,48,64],1):lines.append(f'| {i} | {v} |')
lines+=['','Shop-Verteilung in Prozent:','', '| Level | 1 Gold | 2 Gold | 3 Gold | 4 Gold | 5 Gold |','|---|---|---|---|---|---|']
for i,odds in enumerate([[100,0,0,0,0],[80,20,0,0,0],[65,30,5,0,0],[50,35,15,0,0],[35,35,23,7,0],[25,30,25,17,3],[18,25,27,23,7],[12,20,28,25,15],[8,15,25,32,20],[5,10,25,40,20]],1):lines.append('| '+str(i)+' | '+' | '.join(map(str,odds))+' |')
lines+=['','## Drei Sterne','', 'Bisherige 3-Sterne-Grundskalierung bleibt ×3,24. Darauf kommen abhängig vom ursprünglichen Preis folgende **zusätzlichen** Multiplikatoren; Rabatte haben keinen Einfluss. Rüstung bleibt von dieser zusätzlichen Sternskalierung ausgenommen.','', '| Preis | LP | Angriff | Fähigkeit |','|---|---|---|---|']
for i,row in enumerate([[1.08,1.06,1.10],[1.14,1.12,1.18],[1.25,1.22,1.35],[1.50,1.45,1.70],[2.50,2.20,3.0]],1):lines.append('| '+str(i)+' | '+' | '.join('×'+str(v) for v in row)+' |')
lines+=['','5-Gold-Einheiten mit drei Sternen tragen eine goldene Aura und verstärkte Fähigkeitsmarkierungen. Kein Bonus gewährt permanente Unverwundbarkeit. Kampfende spätestens nach 120 Sekunden.','', '## Roster und Erreichbarkeit','', 'Gen. 1–3 enthalten nur sechs Geist-Linien: Nebulak, Traunfugil, Nincada/Ninjatom, Zobiris, Shuppet und Zwirrlicht. Die freigegebene kleinste Generationserweiterung ist **Schneppke → Frosdedje (Gen. 4)**. Die Auswahl bleibt bei **70 unterschiedlichen Linien**. 20 Linien wurden ausgetauscht; alle behalten reale Typen und vollständige gewählte Entwicklungszweige. Insgesamt 143 unterschiedliche Formen besitzen lokale Idle-Animationen.','', 'Verfügbarkeit zählt jede Linie höchstens einmal, wenn mindestens eine ihrer tatsächlich spielbaren Sternstufen den Typ trägt. Die Sternspalten zeigen, wie viele Linien den Typ auf dieser Stufe gleichzeitig besitzen. So ist zum Beispiel Nincada Boden, Ninjatom dagegen Geist; Azurill verliert bei der Entwicklung Normal. Shop- und Einheiten-Tooltips zeigen die Namen und Typen aller Sternstufen.','', '| Typ | Unterschiedliche verfügbare Linien | 1★ | 2★ | 3★ |','|---|---|---|---|---|']
def form(m,star):return m['forms'][star-1] if len(m['forms'])==3 else m['forms'][-1] if star==3 else m['forms'][0]
for t in traits:
 counts=[sum(t in spec[form(m,s)]['types'] for m in r) for s in [1,2,3]]
 total=sum(any(t in spec[f]['types'] for f in m['forms']) for m in r)
 lines.append(f'| {t} | {total} | '+ ' | '.join(map(str,counts))+' |')
lines+=['', 'Für jeden Typ sind mindestens sieben reale Linien verfügbar. Sieben passende Linien plus ein Typ-Emblem erreichen Stufe 8 innerhalb des Zehner-Teamlimits. Teilweise muss dafür eine frühere Entwicklungsstufe beibehalten werden. Embleme zählen auch ohne natürliche Einheit als +1, erzeugen aber weder Pokémon noch zusätzliche natürliche Typ-Vielfalt. Angebote bleiben ohne Duplikate; Emblem-Gewicht = 1 + min(4, natürliche passende Linien), alle anderen Gewichte 1. Auswahl weiterhin vor Runde 5, 12 und 20.','', 'Neu: '+', '.join(m['name'] for m in r if m['id'] not in {x['id'] for x in old})+'.','', 'Entfernt: '+', '.join(m['name'] for m in old if m['id'] not in {x['id'] for x in r})+'.','', 'Alte Spielstände werden vor Übernahme als `.pre-v8-backup` gesichert. Entfernte Einheiten werden mit ihrem alten Verkaufswert (Preis × Kopienzahl) erstattet; verbleibende Einheiten, Runde, Leben und Fortschritt bleiben erhalten.','', '## Einheitliche Kampfregeln','', 'Zeitbasis: 10 Schritte/s. Normale Angriffe lösen nach 0,2 s aus, Fähigkeiten nach 0,3 s. Unterbrechung oder ein verschwundenes/besiegtes Ziel verwirft die vorbereitete Aktion. Projektilzeit, Treffer und Status folgen derselben Zeitbasis; Pause und Tempo wirken gemeinsam auf Kampf und Effekte. Fähigkeiten unterscheiden sich durch Element, Impakt und Namenseintrag. Bei globalen und Kettenfähigkeiten gilt die Vorbereitung für die gesamte Wirkung.','', 'Gleiche Wasser- und Rissflächen stapeln ihre Boni nicht. Nicht ausdrücklich genannte Boni gelten nur für den jeweiligen Typ. Schildabsorption erfolgt vor LP-Verlust; Gestein-Trait-Schilde werden separat abgebaut. Segen stapeln nicht. Permanente, einmalige Effekte gelten bis Kampfende; zeitlich begrenzte Effekte verwenden die unten genannten Dauern. Tote Einheiten führen keine eigenen Aktionen aus; bereits laufende Felder und Toxin enden regulär. Beschwörungen erhöhen keine Zähler und erzeugen keine weiteren Larven oder Drachen-Todesstapel. Jede natürliche Einheit zählt höchstens einmal als Tod. Wiederkehr bleibt endlich. Alle Kampfobjekte, Felder und temporären Werte werden beim nächsten Kampf neu angelegt.','']
for t,v in traits.items():
 lines+=['### '+t+' – '+v[0],'']+[f'- **{(i+1)*2}:** {desc}' for i,desc in enumerate(v[1:])]+['']
lines+=['## Fokus je Fähigkeit','', 'Stufe 6 skaliert Schaden, Heilung, Schild, Mana-Gabe und Statusdauer auf 150 %. Stufe 8 auf 200 %. Reichweiten und Flächenradien verdoppeln sich bei Stufe 8; globale Ziele bleiben global. Reinigung entfernt weiterhin alle entfernbaren Zustände. Alle höheren Schwellen werden automatisch ausgelöst und vollständig als Mana verbraucht. Zusatzeffekte lösen keine neue Fähigkeit aus. Prozentuale Toxin-Trait-Werte bleiben unverändert.','', '| Pokémon / Fähigkeit | Zusatzeffekt bei 200 % Fokus |','|---|---|']
for m in r:
 e=m['effects'][0];kind=e['kind'];selector=e['target']
 text={'damage':'Zusätzlich 50 % Grundstärke als Fähigkeitsschaden','heal':'Zusätzlich Schild mit 50 % Grundstärke','shield':'Zusätzlich Heilung mit 50 % Grundstärke','mana':'Zusätzlich 15 Mana','cleanse':'Zusätzlich Schild mit 50 % Grundstärke'}.get(kind,'Verdoppelte ursprüngliche Statusdauer plus 1 Sekunde; ursprüngliche Stärke')
 lines.append('| '+m['name']+' / '+m['ability']+' | '+text+'; Zielauswahl `'+selector+'`. |')
lines+=['','Neue Linien besitzen eigene benannte Auto-Battler-Fähigkeiten mit realen Schadens-, Schutz-, Heilungs- oder Statuseffekten. Diese Namen sind Spielgestaltung, keine Behauptung über kanonische Pokémon-Attackennamen.','', '## Prüfung und Grenzen','', '- 1.012 Kernprüfungen: Transaktionen, Pool, Entwicklungen, Auszahlungen, Mana, Fähigkeiten, Speichern, deterministische Kämpfe und sechs Kampagnen.','- 486 neue Prüfungen: alle 18 Traits × vier Schwellen, sieben Linien je Typ, Augments, Interaktionen, Begrenzungen, echte 100-s-Wachstumsphase, Rücksetzen und Save-Migration.','- 471 Bedienprüfungen und 29.897 Layoutprüfungen über sechs Fenstergrößen; 115 zusätzliche Prüfungen für Typ-Dialoge, Kaufbarkeit, Felder und Zustände.','- 39 Perspektivprüfungen mit echtem Windows-Vollbild und Drag-and-drop.','- 838 Animationsprüfungen. 20 Pokémon mit 20 gleichzeitigen Fähigkeiten: Median 16,6 ms, 95. Perzentil 20,1 ms; ohne Effektwelle Median 16,7 ms auf diesem Rechner.','- Die sechste Pflanzenstufe erreicht 20 Stapel bei 100 s; ein echtes Sieben-Linien-Spiegelduell erreichte diesen Wert und wurde beim 120-s-Limit beendet. Das ist ein Effekt für lange Kämpfe, kein garantierter Standardkampf-Bonus.','- Nicht geprüft: Browser-Vollbild in einem ausgelieferten Webexport. Die ausgelieferte Anwendung ist weiterhin Windows-native.','- Die bestehenden Multiplayer-Grenzen bleiben: deterministische Spiellogik und Befehlsschnittstelle, noch kein Netzwerk-Multiplayer.','', 'Quellen: [PokeAPI-Daten](https://github.com/PokeAPI/pokeapi/tree/master/data/v2/csv), [PokeAPI-Sprites](https://github.com/PokeAPI/sprites). Die verwendeten GIFs liefern Idle-Zyklen; Angriff, Treffer, Larve und Fähigkeiten werden durch eigene Pixel-Effekte dargestellt. Neue Assets verwenden denselben gepinnten Commit wie vorher.']
Path('docs/V8-SYSTEME.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
p=Path('README.md');s=p.read_text(encoding='utf-8').replace('Version 7','Version 8',1).replace('140 animierte','143 animierte').replace('52 Augments',str(len(aug))+' Augments').replace('Das Fenster startet mit 1600 × 800; Vergrößern oder F11 verbessert die Darstellung auf großen Bildschirmen.','Das Spiel startet im Vollbild; F11 wechselt zum Fenster.').replace('Neu: korrigierte Textgrenzen','Neu in V8: 18 Typ-Systeme mit 2/4/6/8-Schwellen, Typ-Embleme, neue Wirtschaft, stärkere 3-Sterne-Einheiten und 70 neu abgestimmte Linien mit Frosdedje als freigegebener Gen.-4-Ausnahme. [Werte, Roster, Regeln und Tests](docs/V8-SYSTEME.md).\n\nVorherige UI-Korrekturen: korrigierte Textgrenzen');s=s.replace('Zwei/vier unterschiedliche Linien aktivieren die jeweilige Bonusstufe.','2/4/6/8 unterschiedliche passende Linien einschließlich Typ-Emblemen aktivieren die jeweilige Bonusstufe. Klick auf einen Typ zeigt alle Effekte.');p.write_text(s,encoding='utf-8')
p=Path('tools/build.ps1');s=p.read_text(encoding='utf-8').replace("'V7-UI.md','AUGMENTS.md'","'V7-UI.md','V8-SYSTEME.md','AUGMENTS.md'");p.write_text(s,encoding='utf-8')
manifest=[]
for i in sorted({i for m in r for i in m['forms']}):
 raw=Path(f'assets/pokemon/{i}.png').read_bytes();manifest.append({'id':i,'sha256':hashlib.sha256(raw).hexdigest(),'url':f'https://raw.githubusercontent.com/PokeAPI/sprites/6e523c72bb714306c90912647e0b2ccc4fd2fff1/sprites/pokemon/{i}.png'})
Path('assets/manifest-v8.json').write_text(json.dumps(manifest,indent=2),encoding='utf-8')
p=Path('tools/build.ps1');s=p.read_text(encoding='utf-8').replace("$releaseDocs = Join-Path", "Copy-Item -LiteralPath (Join-Path $project 'assets\\manifest-v8.json') -Destination $release -Force\n$releaseDocs = Join-Path");p.write_text(s,encoding='utf-8')
p=Path('docs/MEDIEN.md');s=p.read_text(encoding='utf-8')+'\n\n## V8\n\n143 aktive Formen aus derselben PokeAPI-Quelle; Hashes und URLs in `assets/manifest-v8.json`, Idle-Zeiten im Animationsmanifest. Freigegebene Ausnahme: Frosdedje (Generation 4). Details in [V8-SYSTEME.md](V8-SYSTEME.md).\n';p.write_text(s,encoding='utf-8')
print('Docs generated; augments',len(aug),'forms',len(manifest))
